### ISSUE TITLE
Feature request: Support event labels and values

### ISSUE THREAD

**Issue by OriginalEXE** [commonlabs-id/next-with-analytics#22]
Hello,

Thank you for creating this useful library! I would like to use the helper functions directly from this package but the `event` helper function does not support all the options of the `react-ga` `event` function.

Would you be willing to accept a PR adding support for the remaining arguments?

Thanks,
Ante

**Comment by resir014** [comment]
@OriginalEXE Hi, sure! PRs for this are always appreciated.
